title: Jack Jazrawy-Brown
author: Jack Jazrawy-Brown
email: jackjazb@gmail.com
description: >-
  Hi, I'm Jack, a UK based software engineer and musician.
  I'm currently writing Rust, TypeScript and React.
baseurl: ""
url: "https://jackjazb.github.io"
github_username: jackjazb
spotify_id: 3Xmb9GKlBKmp97WNc9lOVh

# Build settings
plugins:
  - jekyll-feed
